# Read Data

In [18]:
import json
from pathlib import Path
import pandas as pd

In [12]:
data_folder=Path('./data')

def read_json(file_path):
    with open(file_path, 'r') as f: 
        try: 
            return json.load(f) 
        except json.JSONDecodeError:
            f.seek(0)
            return[json.loads(line) for line in f if line.strip()]

In [14]:
portfolio_data = read_json(data_folder/'portfolio.json')
profile_data = read_json(data_folder/'profile.json')
transcript_data = read_json(data_folder/'transcript.json')

In [17]:
print(type(portfolio_data))

<class 'list'>

In [19]:
portfolio_data = pd.DataFrame(portfolio_data)
profile_data = pd.DataFrame(profile_data)
transcript_data = pd.DataFrame(transcript_data)

In [21]:
portfolio_data

,reward,channels,difficulty,duration,offer_type,id
0,10,"[email, mobile, social]",10,7.0,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,10,"[web, email, mobile, social]",10,5.0,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,0,"[web, email, mobile]",0,4.0,informational,3f207df678b143eea3cee63160fa8bed
3,5,"[web, email, mobile]",5,7.0,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,5,"[web, email]",20,10.0,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7
5,3,"[web, email, mobile, social]",7,7.0,discount,2298d6c36e964ae4a3e7e9706d1fb8c2
6,2,"[web, email, mobile, social]",10,10.0,discount,fafdcd668e3743c1bb461111dcafc2a4
7,0,"[email, mobile, social]",0,3.0,informational,5a8bc65990b245e5a138643cd4eb9837
8,5,"[web, email, mobile, social]",5,5.0,bogo,f19421c1d4aa40978ebb69ca19b0e20d
9,2,"[web, email, mobile]",10,7.0,discount,2906b810c7d4411798c6938adc9daaa5

In [22]:
profile_data

      gender  age                                id became_member_on    income
0       None  118  68be06ca386d4c31939f3a4f0e3dd783         20170212       NaN
1          F   55  0610b486422d4921ae7d2bf64640c50b         20170715  112000.0
2       None  118  38fe809add3b4fcf9315a9694bb96ff5         20180712       NaN
3          F   75  78afa995795e4d85b5d9ceeca43f5fef         20170509  100000.0
4       None  118  a03223e636434f42ac4c3df47e8bac43         20170804       NaN
...      ...  ...                               ...              ...       ...
16995      F   45  6d5f3a774f3d4714ab0c092238f3a1d7         20180604   54000.0
16996      M   61  2cb4f97358b841b9a9773a7aa05a9d77         20180713   72000.0
16997      M   49  01d26f638c274aa0b965d24cefe3183f         20170126   73000.0
16998      F   83  9dc1421481194dcd9400aec7c9ae6366         20160307   50000.0
16999      F   62  e4052622e5ba45a8b96b59aba68cf068         20170722   82000.0

[17000 rows x 5 columns]

In [23]:
transcript_data

,person,event,value,time
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0
...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,transaction,{'amount': 1.59},714
306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,{'amount': 9.53},714
306531,a00058cf10334a308c68e7631c529907,transaction,{'amount': 3.61},714
306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,{'amount': 3.53},714
306533,c02b10e8752c4d8e9b73f918558531f7,transaction,{'amount': 4.05},714